name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: github-pages
          path: site
          if-no-files-found: error
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5